<?php

namespace Admin\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AudioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AudioRepository extends EntityRepository
{
	public function getAll($categorie)  
    {  
        $query = $this->getEntityManager()->createQuery(
        	'SELECT A FROM AdminBundle:Audio A
            WHERE A.categorie = :categorie');

        $query->setParameter('categorie', $categorie);
        return $query->getResult(); 

    } 

      public function getFileNames($id)  
    {  
        $query = $this->getEntityManager()->createQuery(
            'SELECT A FROM AdminBundle:Audio A
            WHERE A.id = :id');
            

        $query->setParameter('id', $id);
        try{
            return $query->getResult();
        }
        catch (\Doctrine\Orm\NoResultException $e) {
            return null;
        }        
    } 
}
