<?php

namespace Admin\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LivresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivresRepository extends EntityRepository
{
	public function getAll($categorie)  
    {  
        $query = $this->getEntityManager()->createQuery(
        	'SELECT A FROM AdminBundle:Livres A
            WHERE A.collection = :categorie');

        $query->setParameter('categorie', $categorie);
        return $query->getResult(); 

    } 


    public function getTwo($sousCat)  
    {  
        $query = $this->getEntityManager()->createQuery(
        	'SELECT A FROM AdminBundle:Livres A
            WHERE A.categorie = :sousCat');
        	

        $query->setParameter('sousCat', $sousCat);
        try{
        	return $query->getResult();
        }
        catch (\Doctrine\Orm\NoResultException $e) {
			return null;
		}        
    } 


    public function getPremiere()  
    {  
        $query = $this->getEntityManager()->createQuery(
            'SELECT A FROM AdminBundle:Livres A
            WHERE A.premiere = true')
            ->setMaxResults(2);

        //$query->setParameter('premiere', $premiere);
        try{
            return $query->getResult();
        }
        catch (\Doctrine\Orm\NoResultException $e) {
            return null;
        }
         

    } 

    
     public function getFileNames($id)  
    {  
        $query = $this->getEntityManager()->createQuery(
            'SELECT A FROM AdminBundle:Livres A
            WHERE A.id = :id');
            

        $query->setParameter('id', $id);
        try{
            return $query->getResult();
        }
        catch (\Doctrine\Orm\NoResultException $e) {
            return null;
        }        
    } 
}
