agenda:
    path:     /
    defaults: { _controller: "AdminBundle:Agenda:index" }

agenda_show:
    path:     /{id}/show
    defaults: { _controller: "AdminBundle:Agenda:show" }

agenda_new:
    path:     /new
    defaults: { _controller: "AdminBundle:Agenda:new" }

agenda_create:
    path:     /create
    defaults: { _controller: "AdminBundle:Agenda:create" }
    methods:  POST

agenda_edit:
    path:     /{id}/edit
    defaults: { _controller: "AdminBundle:Agenda:edit" }

agenda_update:
    path:     /{id}/update
    defaults: { _controller: "AdminBundle:Agenda:update" }
    methods:  [POST, PUT]

agenda_delete:
    path:     /{id}/delete
    defaults: { _controller: "AdminBundle:Agenda:delete" }
    methods:  [POST, DELETE]
